POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "name": "Goutham Reddy",
  "email": "uppinurigoutaeddy@gmail.com",
  "password": "123",
  "confirmPassword": "123"
}
###
POST http://localhost:4000/api/survey/update-product-metrics
Content-Type: application/json

{
  "productId":"6737128df28bba4b5ad08e79",
  "userId":"67339ae19c196f9a7bea8ae5",
  "viewedTime":1000,
  "startTime":"22:50",
  "endTime":"22:51"
}
###
POST http://localhost:4000/api/survey/add-survey-question
Content-Type: application/json

{
  "productId":"6737132bf28bba4b5ad08e86",
  "questions":[
                {
                    "question": "Why did you remove this product from your cart?",
                    "type": "multiple-choice",
                    "options": ["Too expensive", "Found a better alternative", "Changed my mind"]
                },
                {
                    "question": "Any additional feedback?",
                    "type": "text"
                }
            ]
}

###
POST http://localhost:4000/api/survey/get-form-details
Content-Type: application/json

{
  "productId":"6737132bf28bba4b5ad08e86"
}
###
POST http://localhost:4000/api/survey/submit-survey-answer
Content-Type: application/json

{
  "productId": "6489f9d4f8c9001123456781",
  "userId": "6489f9d4f8c9001123456780",
  "userDetails": {
  },
  "responses": [
    {
      "question": "Why did you remove this product from your cart?",
      "answer": "Too expensive"
    },
    {
      "question": "What feature would make you reconsider buying it?",
      "answer": "Better discounts"
    },
    {
      "question": "Any additional feedback?",
      "answer": "Great product, but price is a concern"
    }
  ]
}

###
POST http://localhost:4000/api/survey/submitForm
Content-Type: application/json

{
  "name":"goutham",
  "email":"gouth@gmail.com",
  "mobile":"9398141936",
  "issue":"website so bad."
}
###
POST http://localhost:4000/api/survey/deleteTicket
Content-Type: application/json

{
  "id":"675e96ce11f3a31bff0e2c67"
}
###
POST http://localhost:4000/api/product/get
Content-Type: application/json

{
  "search":"thor"
}
###
POST http://localhost:4000/api/subcategory/get
Content-Type: application/json

{
  "name":"Premiere Pro Templates"
}
###
POST http://localhost:4000/api/subcategory/get
Content-Type: application/json

{
}